// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'media_stream.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_MediaStream _$MediaStreamFromJson(Map<String, dynamic> json) => _MediaStream(
  nalLengthSize: json['NalLengthSize'] as String?,
  codecTag: json['CodecTag'] as String?,
  language: json['Language'] as String?,
  colorRange: json['ColorRange'] as String?,
  colorSpace: json['ColorSpace'] as String?,
  colorTransfer: json['ColorTransfer'] as String?,
  colorPrimaries: json['ColorPrimaries'] as String?,
  dvVersionMajor: (json['DvVersionMajor'] as num?)?.toInt(),
  dvVersionMinor: (json['DvVersionMinor'] as num?)?.toInt(),
  dvProfile: (json['DvProfile'] as num?)?.toInt(),
  dvLevel: (json['DvLevel'] as num?)?.toInt(),
  rpuPresentFlag: (json['RpuPresentFlag'] as num?)?.toInt(),
  elPresentFlag: (json['ElPresentFlag'] as num?)?.toInt(),
  blPresentFlag: (json['BlPresentFlag'] as num?)?.toInt(),
  dvBlSignalCompatibilityId: (json['DvBlSignalCompatibilityId'] as num?)
      ?.toInt(),
  rotation: (json['Rotation'] as num?)?.toInt(),
  comment: json['Comment'] as String?,
  timeBase: json['TimeBase'] as String?,
  codecTimeBase: json['CodecTimeBase'] as String?,
  title: json['Title'] as String?,
  hdr10PlusPresentFlag: json['Hdr10PlusPresentFlag'] as bool?,
  codec: json['Codec'] as String?,
  level: (json['Level'] as num?)?.toDouble(),
  videoDoViTitle: json['VideoDoViTitle'] as String?,
  pixelFormat: json['PixelFormat'] as String?,
  localizedUndefined: json['LocalizedUndefined'] as String?,
  localizedDefault: json['LocalizedDefault'] as String?,
  localizedForced: json['LocalizedForced'] as String?,
  localizedExternal: json['LocalizedExternal'] as String?,
  localizedHearingImpaired: json['LocalizedHearingImpaired'] as String?,
  displayTitle: json['DisplayTitle'] as String?,
  isDefault: json['IsDefault'] as bool,
  isInterlaced: json['IsInterlaced'] as bool,
  isAvc: json['IsAVC'] as bool?,
  channelLayout: json['ChannelLayout'] as String?,
  bitRate: (json['BitRate'] as num?)?.toInt(),
  bitDepth: (json['BitDepth'] as num?)?.toInt(),
  refFrames: (json['RefFrames'] as num?)?.toInt(),
  packetLength: (json['PacketLength'] as num?)?.toInt(),
  channels: (json['Channels'] as num?)?.toInt(),
  sampleRate: (json['SampleRate'] as num?)?.toInt(),
  isAnamorphic: json['IsAnamorphic'] as bool?,
  isForced: json['IsForced'] as bool,
  isHearingImpaired: json['IsHearingImpaired'] as bool,
  height: (json['Height'] as num?)?.toInt(),
  width: (json['Width'] as num?)?.toInt(),
  averageFrameRate: (json['AverageFrameRate'] as num?)?.toDouble(),
  realFrameRate: (json['RealFrameRate'] as num?)?.toDouble(),
  referenceFrameRate: (json['ReferenceFrameRate'] as num?)?.toDouble(),
  profile: json['Profile'] as String?,
  type: $enumDecode(_$MediaStreamTypeEnumMap, json['Type']),
  aspectRatio: json['AspectRatio'] as String?,
  index: (json['Index'] as num).toInt(),
  path: json['Path'] as String?,
  isExternal: json['IsExternal'] as bool,
  deliveryMethod: $enumDecodeNullable(
    _$MediaStreamDeliveryMethodEnumMap,
    json['DeliveryMethod'],
  ),
  deliveryUrl: json['DeliveryUrl'] as String?,
  isExternalUrl: json['IsExternalUrl'] as bool?,
  isTextSubtitleStream: json['IsTextSubtitleStream'] as bool,
  supportsExternalStream: json['SupportsExternalStream'] as bool,
  score: (json['Score'] as num?)?.toInt(),
  audioSpatialFormat:
      $enumDecodeNullable(
        _$MediaStreamAudioSpatialFormatEnumMap,
        json['AudioSpatialFormat'],
      ) ??
      MediaStreamAudioSpatialFormat.none,
  videoRangeType:
      $enumDecodeNullable(
        _$MediaStreamVideoRangeTypeEnumMap,
        json['VideoRangeType'],
      ) ??
      MediaStreamVideoRangeType.unknown,
  videoRange:
      $enumDecodeNullable(_$MediaStreamVideoRangeEnumMap, json['VideoRange']) ??
      MediaStreamVideoRange.unknown,
);

Map<String, dynamic> _$MediaStreamToJson(_MediaStream instance) =>
    <String, dynamic>{
      'NalLengthSize': ?instance.nalLengthSize,
      'CodecTag': ?instance.codecTag,
      'Language': ?instance.language,
      'ColorRange': ?instance.colorRange,
      'ColorSpace': ?instance.colorSpace,
      'ColorTransfer': ?instance.colorTransfer,
      'ColorPrimaries': ?instance.colorPrimaries,
      'DvVersionMajor': ?instance.dvVersionMajor,
      'DvVersionMinor': ?instance.dvVersionMinor,
      'DvProfile': ?instance.dvProfile,
      'DvLevel': ?instance.dvLevel,
      'RpuPresentFlag': ?instance.rpuPresentFlag,
      'ElPresentFlag': ?instance.elPresentFlag,
      'BlPresentFlag': ?instance.blPresentFlag,
      'DvBlSignalCompatibilityId': ?instance.dvBlSignalCompatibilityId,
      'Rotation': ?instance.rotation,
      'Comment': ?instance.comment,
      'TimeBase': ?instance.timeBase,
      'CodecTimeBase': ?instance.codecTimeBase,
      'Title': ?instance.title,
      'Hdr10PlusPresentFlag': ?instance.hdr10PlusPresentFlag,
      'Codec': ?instance.codec,
      'Level': ?instance.level,
      'VideoDoViTitle': ?instance.videoDoViTitle,
      'PixelFormat': ?instance.pixelFormat,
      'LocalizedUndefined': ?instance.localizedUndefined,
      'LocalizedDefault': ?instance.localizedDefault,
      'LocalizedForced': ?instance.localizedForced,
      'LocalizedExternal': ?instance.localizedExternal,
      'LocalizedHearingImpaired': ?instance.localizedHearingImpaired,
      'DisplayTitle': ?instance.displayTitle,
      'IsDefault': instance.isDefault,
      'IsInterlaced': instance.isInterlaced,
      'IsAVC': ?instance.isAvc,
      'ChannelLayout': ?instance.channelLayout,
      'BitRate': ?instance.bitRate,
      'BitDepth': ?instance.bitDepth,
      'RefFrames': ?instance.refFrames,
      'PacketLength': ?instance.packetLength,
      'Channels': ?instance.channels,
      'SampleRate': ?instance.sampleRate,
      'IsAnamorphic': ?instance.isAnamorphic,
      'IsForced': instance.isForced,
      'IsHearingImpaired': instance.isHearingImpaired,
      'Height': ?instance.height,
      'Width': ?instance.width,
      'AverageFrameRate': ?instance.averageFrameRate,
      'RealFrameRate': ?instance.realFrameRate,
      'ReferenceFrameRate': ?instance.referenceFrameRate,
      'Profile': ?instance.profile,
      'Type': instance.type.toJson(),
      'AspectRatio': ?instance.aspectRatio,
      'Index': instance.index,
      'Path': ?instance.path,
      'IsExternal': instance.isExternal,
      'DeliveryMethod': ?instance.deliveryMethod?.toJson(),
      'DeliveryUrl': ?instance.deliveryUrl,
      'IsExternalUrl': ?instance.isExternalUrl,
      'IsTextSubtitleStream': instance.isTextSubtitleStream,
      'SupportsExternalStream': instance.supportsExternalStream,
      'Score': ?instance.score,
      'AudioSpatialFormat': instance.audioSpatialFormat.toJson(),
      'VideoRangeType': instance.videoRangeType.toJson(),
      'VideoRange': instance.videoRange.toJson(),
    };

const _$MediaStreamTypeEnumMap = {
  MediaStreamType.audio: 'Audio',
  MediaStreamType.video: 'Video',
  MediaStreamType.subtitle: 'Subtitle',
  MediaStreamType.embeddedImage: 'EmbeddedImage',
  MediaStreamType.data: 'Data',
  MediaStreamType.lyric: 'Lyric',
};

const _$MediaStreamDeliveryMethodEnumMap = {
  MediaStreamDeliveryMethod.encode: 'Encode',
  MediaStreamDeliveryMethod.embed: 'Embed',
  MediaStreamDeliveryMethod.valueExternal: 'External',
  MediaStreamDeliveryMethod.hls: 'Hls',
  MediaStreamDeliveryMethod.drop: 'Drop',
};

const _$MediaStreamAudioSpatialFormatEnumMap = {
  MediaStreamAudioSpatialFormat.none: 'None',
  MediaStreamAudioSpatialFormat.dolbyAtmos: 'DolbyAtmos',
  MediaStreamAudioSpatialFormat.dtsx: 'DTSX',
};

const _$MediaStreamVideoRangeTypeEnumMap = {
  MediaStreamVideoRangeType.unknown: 'Unknown',
  MediaStreamVideoRangeType.sdr: 'SDR',
  MediaStreamVideoRangeType.hdr10: 'HDR10',
  MediaStreamVideoRangeType.hlg: 'HLG',
  MediaStreamVideoRangeType.dovi: 'DOVI',
  MediaStreamVideoRangeType.doviWithHdr10: 'DOVIWithHDR10',
  MediaStreamVideoRangeType.doviWithHlg: 'DOVIWithHLG',
  MediaStreamVideoRangeType.doviWithSdr: 'DOVIWithSDR',
  MediaStreamVideoRangeType.doviWithEl: 'DOVIWithEL',
  MediaStreamVideoRangeType.doviWithHdr10Plus: 'DOVIWithHDR10Plus',
  MediaStreamVideoRangeType.doviWithElhdr10Plus: 'DOVIWithELHDR10Plus',
  MediaStreamVideoRangeType.doviInvalid: 'DOVIInvalid',
  MediaStreamVideoRangeType.hdr10Plus: 'HDR10Plus',
};

const _$MediaStreamVideoRangeEnumMap = {
  MediaStreamVideoRange.unknown: 'Unknown',
  MediaStreamVideoRange.sdr: 'SDR',
  MediaStreamVideoRange.hdr: 'HDR',
};
