// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'media_stream.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_MediaStream _$MediaStreamFromJson(Map<String, dynamic> json) => _MediaStream(
  isDefault: json['IsDefault'] as bool,
  videoRange: MediaStreamVideoRange.fromJson(json['VideoRange']),
  isTextSubtitleStream: json['IsTextSubtitleStream'] as bool,
  isExternal: json['IsExternal'] as bool,
  index: (json['Index'] as num).toInt(),
  type: MediaStreamType.fromJson(json['Type']),
  isHearingImpaired: json['IsHearingImpaired'] as bool,
  isForced: json['IsForced'] as bool,
  isInterlaced: json['IsInterlaced'] as bool,
  audioSpatialFormat: MediaStreamAudioSpatialFormat.fromJson(
    json['AudioSpatialFormat'],
  ),
  supportsExternalStream: json['SupportsExternalStream'] as bool,
  videoRangeType: MediaStreamVideoRangeType.fromJson(json['VideoRangeType']),
  elPresentFlag: (json['ElPresentFlag'] as num?)?.toInt(),
  blPresentFlag: (json['BlPresentFlag'] as num?)?.toInt(),
  dvBlSignalCompatibilityId: (json['DvBlSignalCompatibilityId'] as num?)
      ?.toInt(),
  rotation: (json['Rotation'] as num?)?.toInt(),
  comment: json['Comment'] as String?,
  timeBase: json['TimeBase'] as String?,
  codecTimeBase: json['CodecTimeBase'] as String?,
  title: json['Title'] as String?,
  hdr10PlusPresentFlag: json['Hdr10PlusPresentFlag'] as bool?,
  codec: json['Codec'] as String?,
  rpuPresentFlag: (json['RpuPresentFlag'] as num?)?.toInt(),
  videoDoViTitle: json['VideoDoViTitle'] as String?,
  dvProfile: (json['DvProfile'] as num?)?.toInt(),
  localizedUndefined: json['LocalizedUndefined'] as String?,
  localizedDefault: json['LocalizedDefault'] as String?,
  localizedForced: json['LocalizedForced'] as String?,
  localizedExternal: json['LocalizedExternal'] as String?,
  localizedHearingImpaired: json['LocalizedHearingImpaired'] as String?,
  displayTitle: json['DisplayTitle'] as String?,
  dvLevel: (json['DvLevel'] as num?)?.toInt(),
  dvVersionMinor: (json['DvVersionMinor'] as num?)?.toInt(),
  isAvc: json['IsAVC'] as bool?,
  channelLayout: json['ChannelLayout'] as String?,
  bitRate: (json['BitRate'] as num?)?.toInt(),
  bitDepth: (json['BitDepth'] as num?)?.toInt(),
  refFrames: (json['RefFrames'] as num?)?.toInt(),
  packetLength: (json['PacketLength'] as num?)?.toInt(),
  channels: (json['Channels'] as num?)?.toInt(),
  sampleRate: (json['SampleRate'] as num?)?.toInt(),
  isAnamorphic: json['IsAnamorphic'] as bool?,
  dvVersionMajor: (json['DvVersionMajor'] as num?)?.toInt(),
  colorPrimaries: json['ColorPrimaries'] as String?,
  height: (json['Height'] as num?)?.toInt(),
  width: (json['Width'] as num?)?.toInt(),
  averageFrameRate: (json['AverageFrameRate'] as num?)?.toDouble(),
  realFrameRate: (json['RealFrameRate'] as num?)?.toDouble(),
  referenceFrameRate: (json['ReferenceFrameRate'] as num?)?.toDouble(),
  profile: json['Profile'] as String?,
  colorTransfer: json['ColorTransfer'] as String?,
  aspectRatio: json['AspectRatio'] as String?,
  colorSpace: json['ColorSpace'] as String?,
  score: (json['Score'] as num?)?.toInt(),
  colorRange: json['ColorRange'] as String?,
  deliveryMethod: json['DeliveryMethod'] == null
      ? null
      : MediaStreamDeliveryMethod.fromJson(json['DeliveryMethod']),
  deliveryUrl: json['DeliveryUrl'] as String?,
  isExternalUrl: json['IsExternalUrl'] as bool?,
  language: json['Language'] as String?,
  codecTag: json['CodecTag'] as String?,
  path: json['Path'] as String?,
  pixelFormat: json['PixelFormat'] as String?,
  level: (json['Level'] as num?)?.toDouble(),
  nalLengthSize: json['NalLengthSize'] as String?,
);

Map<String, dynamic> _$MediaStreamToJson(_MediaStream instance) =>
    <String, dynamic>{
      'IsDefault': instance.isDefault,
      'VideoRange': instance.videoRange.toJson(),
      'IsTextSubtitleStream': instance.isTextSubtitleStream,
      'IsExternal': instance.isExternal,
      'Index': instance.index,
      'Type': instance.type.toJson(),
      'IsHearingImpaired': instance.isHearingImpaired,
      'IsForced': instance.isForced,
      'IsInterlaced': instance.isInterlaced,
      'AudioSpatialFormat': instance.audioSpatialFormat.toJson(),
      'SupportsExternalStream': instance.supportsExternalStream,
      'VideoRangeType': instance.videoRangeType.toJson(),
      'ElPresentFlag': ?instance.elPresentFlag,
      'BlPresentFlag': ?instance.blPresentFlag,
      'DvBlSignalCompatibilityId': ?instance.dvBlSignalCompatibilityId,
      'Rotation': ?instance.rotation,
      'Comment': ?instance.comment,
      'TimeBase': ?instance.timeBase,
      'CodecTimeBase': ?instance.codecTimeBase,
      'Title': ?instance.title,
      'Hdr10PlusPresentFlag': ?instance.hdr10PlusPresentFlag,
      'Codec': ?instance.codec,
      'RpuPresentFlag': ?instance.rpuPresentFlag,
      'VideoDoViTitle': ?instance.videoDoViTitle,
      'DvProfile': ?instance.dvProfile,
      'LocalizedUndefined': ?instance.localizedUndefined,
      'LocalizedDefault': ?instance.localizedDefault,
      'LocalizedForced': ?instance.localizedForced,
      'LocalizedExternal': ?instance.localizedExternal,
      'LocalizedHearingImpaired': ?instance.localizedHearingImpaired,
      'DisplayTitle': ?instance.displayTitle,
      'DvLevel': ?instance.dvLevel,
      'DvVersionMinor': ?instance.dvVersionMinor,
      'IsAVC': ?instance.isAvc,
      'ChannelLayout': ?instance.channelLayout,
      'BitRate': ?instance.bitRate,
      'BitDepth': ?instance.bitDepth,
      'RefFrames': ?instance.refFrames,
      'PacketLength': ?instance.packetLength,
      'Channels': ?instance.channels,
      'SampleRate': ?instance.sampleRate,
      'IsAnamorphic': ?instance.isAnamorphic,
      'DvVersionMajor': ?instance.dvVersionMajor,
      'ColorPrimaries': ?instance.colorPrimaries,
      'Height': ?instance.height,
      'Width': ?instance.width,
      'AverageFrameRate': ?instance.averageFrameRate,
      'RealFrameRate': ?instance.realFrameRate,
      'ReferenceFrameRate': ?instance.referenceFrameRate,
      'Profile': ?instance.profile,
      'ColorTransfer': ?instance.colorTransfer,
      'AspectRatio': ?instance.aspectRatio,
      'ColorSpace': ?instance.colorSpace,
      'Score': ?instance.score,
      'ColorRange': ?instance.colorRange,
      'DeliveryMethod': ?instance.deliveryMethod?.toJson(),
      'DeliveryUrl': ?instance.deliveryUrl,
      'IsExternalUrl': ?instance.isExternalUrl,
      'Language': ?instance.language,
      'CodecTag': ?instance.codecTag,
      'Path': ?instance.path,
      'PixelFormat': ?instance.pixelFormat,
      'Level': ?instance.level,
      'NalLengthSize': ?instance.nalLengthSize,
    };
