// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dynamic_hls_client.dart';

// dart format off

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

// ignore_for_file: unnecessary_brace_in_string_interps,no_leading_underscores_for_local_identifiers,unused_element,unnecessary_string_interpolations,unused_element_parameter,avoid_unused_constructor_parameters,unreachable_from_main

class _DynamicHlsClient implements DynamicHlsClient {
  _DynamicHlsClient(this._dio, {this.baseUrl, this.errorLogger});

  final Dio _dio;

  String? baseUrl;

  final ParseErrorLogger? errorLogger;

  @override
  Stream<String> getHlsAudioSegment({
    required String itemId,
    required String playlistId,
    required int segmentId,
    required String container,
    required int runtimeTicks,
    required int actualSegmentLengthTicks,
    bool? allowVideoStreamCopy,
    String? params,
    String? tag,
    String? deviceProfileId,
    String? playSessionId,
    String? segmentContainer,
    int? segmentLength,
    int? minSegments,
    String? mediaSourceId,
    String? deviceId,
    String? audioCodec,
    bool? enableAutoStreamCopy,
    bool? staticValue,
    bool? allowAudioStreamCopy,
    bool? breakOnNonKeyFrames,
    int? audioSampleRate,
    int? maxAudioBitDepth,
    int? maxStreamingBitrate,
    int? audioBitRate,
    int? audioChannels,
    int? maxAudioChannels,
    String? profile,
    String? level,
    double? framerate,
    double? maxFramerate,
    bool? copyTimestamps,
    int? startTimeTicks,
    int? width,
    int? height,
    int? videoBitRate,
    Map<String, String?>? streamOptions,
    SubtitleMethod? subtitleMethod,
    int? maxRefFrames,
    int? maxVideoBitDepth,
    bool? requireAvc,
    bool? deInterlace,
    bool? requireNonAnamorphic,
    int? transcodingMaxAudioChannels,
    int? cpuCoreLimit,
    String? liveStreamId,
    bool? enableMpegtsM2TsMode,
    String? videoCodec,
    String? subtitleCodec,
    String? transcodeReasons,
    int? audioStreamIndex,
    int? videoStreamIndex,
    Context? context,
    int? subtitleStreamIndex,
    bool? enableAudioVbrEncoding = true,
    RequestOptions? options,
  }) async* {
    final _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'runtimeTicks': runtimeTicks,
      r'actualSegmentLengthTicks': actualSegmentLengthTicks,
      r'allowVideoStreamCopy': allowVideoStreamCopy,
      r'params': params,
      r'tag': tag,
      r'deviceProfileId': deviceProfileId,
      r'playSessionId': playSessionId,
      r'segmentContainer': segmentContainer,
      r'segmentLength': segmentLength,
      r'minSegments': minSegments,
      r'mediaSourceId': mediaSourceId,
      r'deviceId': deviceId,
      r'audioCodec': audioCodec,
      r'enableAutoStreamCopy': enableAutoStreamCopy,
      r'static': staticValue,
      r'allowAudioStreamCopy': allowAudioStreamCopy,
      r'breakOnNonKeyFrames': breakOnNonKeyFrames,
      r'audioSampleRate': audioSampleRate,
      r'maxAudioBitDepth': maxAudioBitDepth,
      r'maxStreamingBitrate': maxStreamingBitrate,
      r'audioBitRate': audioBitRate,
      r'audioChannels': audioChannels,
      r'maxAudioChannels': maxAudioChannels,
      r'profile': profile,
      r'level': level,
      r'framerate': framerate,
      r'maxFramerate': maxFramerate,
      r'copyTimestamps': copyTimestamps,
      r'startTimeTicks': startTimeTicks,
      r'width': width,
      r'height': height,
      r'videoBitRate': videoBitRate,
      r'streamOptions': streamOptions,
      r'subtitleMethod': subtitleMethod?.toJson(),
      r'maxRefFrames': maxRefFrames,
      r'maxVideoBitDepth': maxVideoBitDepth,
      r'requireAvc': requireAvc,
      r'deInterlace': deInterlace,
      r'requireNonAnamorphic': requireNonAnamorphic,
      r'transcodingMaxAudioChannels': transcodingMaxAudioChannels,
      r'cpuCoreLimit': cpuCoreLimit,
      r'liveStreamId': liveStreamId,
      r'enableMpegtsM2TsMode': enableMpegtsM2TsMode,
      r'videoCodec': videoCodec,
      r'subtitleCodec': subtitleCodec,
      r'transcodeReasons': transcodeReasons,
      r'audioStreamIndex': audioStreamIndex,
      r'videoStreamIndex': videoStreamIndex,
      r'context': context?.toJson(),
      r'subtitleStreamIndex': subtitleStreamIndex,
      r'enableAudioVbrEncoding': enableAudioVbrEncoding,
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _headers = <String, dynamic>{};
    const Map<String, dynamic>? _data = null;
    final newOptions = newRequestOptions(options);
    newOptions.extra.addAll(_extra);
    newOptions.headers.addAll(_dio.options.headers);
    newOptions.headers.addAll(_headers);
    final _options = newOptions.copyWith(
      method: 'GET',
      baseUrl: _combineBaseUrls(_dio.options.baseUrl, baseUrl),
      responseType: ResponseType.stream,
      queryParameters: queryParameters,
      path: '/Audio/${itemId}/hls1/${playlistId}/${segmentId}.${container}',
    )..data = _data;
    final _result = await _dio.fetch<ResponseBody>(_options);
    final _value = _result.data!.stream.map(utf8.decode);
    yield* _value;
  }

  @override
  Stream<String> getVariantHlsAudioPlaylist({
    required String itemId,
    int? audioSampleRate,
    String? params,
    String? tag,
    String? deviceProfileId,
    String? playSessionId,
    String? segmentContainer,
    int? segmentLength,
    int? minSegments,
    String? mediaSourceId,
    String? deviceId,
    String? audioCodec,
    bool? enableAutoStreamCopy,
    bool? allowVideoStreamCopy,
    bool? allowAudioStreamCopy,
    bool? breakOnNonKeyFrames,
    bool? staticValue,
    int? maxAudioBitDepth,
    int? maxStreamingBitrate,
    int? audioBitRate,
    int? audioChannels,
    int? maxAudioChannels,
    String? profile,
    String? level,
    double? framerate,
    double? maxFramerate,
    bool? copyTimestamps,
    int? startTimeTicks,
    int? width,
    int? height,
    int? videoBitRate,
    int? subtitleStreamIndex,
    Map<String, String?>? streamOptions,
    int? maxRefFrames,
    int? maxVideoBitDepth,
    bool? requireAvc,
    bool? deInterlace,
    bool? requireNonAnamorphic,
    int? transcodingMaxAudioChannels,
    int? cpuCoreLimit,
    String? liveStreamId,
    bool? enableMpegtsM2TsMode,
    String? videoCodec,
    String? subtitleCodec,
    String? transcodeReasons,
    int? audioStreamIndex,
    int? videoStreamIndex,
    Context? context,
    SubtitleMethod? subtitleMethod,
    bool? enableAudioVbrEncoding = true,
    RequestOptions? options,
  }) async* {
    final _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'audioSampleRate': audioSampleRate,
      r'params': params,
      r'tag': tag,
      r'deviceProfileId': deviceProfileId,
      r'playSessionId': playSessionId,
      r'segmentContainer': segmentContainer,
      r'segmentLength': segmentLength,
      r'minSegments': minSegments,
      r'mediaSourceId': mediaSourceId,
      r'deviceId': deviceId,
      r'audioCodec': audioCodec,
      r'enableAutoStreamCopy': enableAutoStreamCopy,
      r'allowVideoStreamCopy': allowVideoStreamCopy,
      r'allowAudioStreamCopy': allowAudioStreamCopy,
      r'breakOnNonKeyFrames': breakOnNonKeyFrames,
      r'static': staticValue,
      r'maxAudioBitDepth': maxAudioBitDepth,
      r'maxStreamingBitrate': maxStreamingBitrate,
      r'audioBitRate': audioBitRate,
      r'audioChannels': audioChannels,
      r'maxAudioChannels': maxAudioChannels,
      r'profile': profile,
      r'level': level,
      r'framerate': framerate,
      r'maxFramerate': maxFramerate,
      r'copyTimestamps': copyTimestamps,
      r'startTimeTicks': startTimeTicks,
      r'width': width,
      r'height': height,
      r'videoBitRate': videoBitRate,
      r'subtitleStreamIndex': subtitleStreamIndex,
      r'streamOptions': streamOptions,
      r'maxRefFrames': maxRefFrames,
      r'maxVideoBitDepth': maxVideoBitDepth,
      r'requireAvc': requireAvc,
      r'deInterlace': deInterlace,
      r'requireNonAnamorphic': requireNonAnamorphic,
      r'transcodingMaxAudioChannels': transcodingMaxAudioChannels,
      r'cpuCoreLimit': cpuCoreLimit,
      r'liveStreamId': liveStreamId,
      r'enableMpegtsM2TsMode': enableMpegtsM2TsMode,
      r'videoCodec': videoCodec,
      r'subtitleCodec': subtitleCodec,
      r'transcodeReasons': transcodeReasons,
      r'audioStreamIndex': audioStreamIndex,
      r'videoStreamIndex': videoStreamIndex,
      r'context': context?.toJson(),
      r'subtitleMethod': subtitleMethod?.toJson(),
      r'enableAudioVbrEncoding': enableAudioVbrEncoding,
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _headers = <String, dynamic>{};
    const Map<String, dynamic>? _data = null;
    final newOptions = newRequestOptions(options);
    newOptions.extra.addAll(_extra);
    newOptions.headers.addAll(_dio.options.headers);
    newOptions.headers.addAll(_headers);
    final _options = newOptions.copyWith(
      method: 'GET',
      baseUrl: _combineBaseUrls(_dio.options.baseUrl, baseUrl),
      responseType: ResponseType.stream,
      queryParameters: queryParameters,
      path: '/Audio/${itemId}/main.m3u8',
    )..data = _data;
    final _result = await _dio.fetch<ResponseBody>(_options);
    final _value = _result.data!.stream.map(utf8.decode);
    yield* _value;
  }

  @override
  Stream<String> getMasterHlsAudioPlaylist({
    required String itemId,
    required String mediaSourceId,
    int? maxAudioBitDepth,
    String? tag,
    String? deviceProfileId,
    String? playSessionId,
    String? segmentContainer,
    int? segmentLength,
    int? minSegments,
    bool? staticValue,
    String? deviceId,
    String? audioCodec,
    bool? enableAutoStreamCopy,
    bool? allowVideoStreamCopy,
    bool? allowAudioStreamCopy,
    bool? breakOnNonKeyFrames,
    int? audioSampleRate,
    String? params,
    int? maxStreamingBitrate,
    int? audioBitRate,
    int? audioChannels,
    int? maxAudioChannels,
    String? profile,
    String? level,
    double? framerate,
    double? maxFramerate,
    bool? copyTimestamps,
    int? startTimeTicks,
    int? width,
    int? height,
    int? videoBitRate,
    int? subtitleStreamIndex,
    SubtitleMethod? subtitleMethod,
    Map<String, String?>? streamOptions,
    int? maxVideoBitDepth,
    bool? requireAvc,
    bool? deInterlace,
    bool? requireNonAnamorphic,
    int? transcodingMaxAudioChannels,
    int? cpuCoreLimit,
    String? liveStreamId,
    bool? enableMpegtsM2TsMode,
    String? videoCodec,
    String? subtitleCodec,
    String? transcodeReasons,
    int? audioStreamIndex,
    int? videoStreamIndex,
    Context? context,
    int? maxRefFrames,
    bool? enableAdaptiveBitrateStreaming = false,
    bool? enableAudioVbrEncoding = true,
    RequestOptions? options,
  }) async* {
    final _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'mediaSourceId': mediaSourceId,
      r'maxAudioBitDepth': maxAudioBitDepth,
      r'tag': tag,
      r'deviceProfileId': deviceProfileId,
      r'playSessionId': playSessionId,
      r'segmentContainer': segmentContainer,
      r'segmentLength': segmentLength,
      r'minSegments': minSegments,
      r'static': staticValue,
      r'deviceId': deviceId,
      r'audioCodec': audioCodec,
      r'enableAutoStreamCopy': enableAutoStreamCopy,
      r'allowVideoStreamCopy': allowVideoStreamCopy,
      r'allowAudioStreamCopy': allowAudioStreamCopy,
      r'breakOnNonKeyFrames': breakOnNonKeyFrames,
      r'audioSampleRate': audioSampleRate,
      r'params': params,
      r'maxStreamingBitrate': maxStreamingBitrate,
      r'audioBitRate': audioBitRate,
      r'audioChannels': audioChannels,
      r'maxAudioChannels': maxAudioChannels,
      r'profile': profile,
      r'level': level,
      r'framerate': framerate,
      r'maxFramerate': maxFramerate,
      r'copyTimestamps': copyTimestamps,
      r'startTimeTicks': startTimeTicks,
      r'width': width,
      r'height': height,
      r'videoBitRate': videoBitRate,
      r'subtitleStreamIndex': subtitleStreamIndex,
      r'subtitleMethod': subtitleMethod?.toJson(),
      r'streamOptions': streamOptions,
      r'maxVideoBitDepth': maxVideoBitDepth,
      r'requireAvc': requireAvc,
      r'deInterlace': deInterlace,
      r'requireNonAnamorphic': requireNonAnamorphic,
      r'transcodingMaxAudioChannels': transcodingMaxAudioChannels,
      r'cpuCoreLimit': cpuCoreLimit,
      r'liveStreamId': liveStreamId,
      r'enableMpegtsM2TsMode': enableMpegtsM2TsMode,
      r'videoCodec': videoCodec,
      r'subtitleCodec': subtitleCodec,
      r'transcodeReasons': transcodeReasons,
      r'audioStreamIndex': audioStreamIndex,
      r'videoStreamIndex': videoStreamIndex,
      r'context': context?.toJson(),
      r'maxRefFrames': maxRefFrames,
      r'enableAdaptiveBitrateStreaming': enableAdaptiveBitrateStreaming,
      r'enableAudioVbrEncoding': enableAudioVbrEncoding,
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _headers = <String, dynamic>{};
    const Map<String, dynamic>? _data = null;
    final newOptions = newRequestOptions(options);
    newOptions.extra.addAll(_extra);
    newOptions.headers.addAll(_dio.options.headers);
    newOptions.headers.addAll(_headers);
    final _options = newOptions.copyWith(
      method: 'GET',
      baseUrl: _combineBaseUrls(_dio.options.baseUrl, baseUrl),
      responseType: ResponseType.stream,
      queryParameters: queryParameters,
      path: '/Audio/${itemId}/master.m3u8',
    )..data = _data;
    final _result = await _dio.fetch<ResponseBody>(_options);
    final _value = _result.data!.stream.map(utf8.decode);
    yield* _value;
  }

  @override
  Stream<String> headMasterHlsAudioPlaylist({
    required String itemId,
    required String mediaSourceId,
    int? maxAudioBitDepth,
    String? tag,
    String? deviceProfileId,
    String? playSessionId,
    String? segmentContainer,
    int? segmentLength,
    int? minSegments,
    bool? staticValue,
    String? deviceId,
    String? audioCodec,
    bool? enableAutoStreamCopy,
    bool? allowVideoStreamCopy,
    bool? allowAudioStreamCopy,
    bool? breakOnNonKeyFrames,
    int? audioSampleRate,
    String? params,
    int? maxStreamingBitrate,
    int? audioBitRate,
    int? audioChannels,
    int? maxAudioChannels,
    String? profile,
    String? level,
    double? framerate,
    double? maxFramerate,
    bool? copyTimestamps,
    int? startTimeTicks,
    int? width,
    int? height,
    int? videoBitRate,
    int? subtitleStreamIndex,
    SubtitleMethod? subtitleMethod,
    Map<String, String?>? streamOptions,
    int? maxVideoBitDepth,
    bool? requireAvc,
    bool? deInterlace,
    bool? requireNonAnamorphic,
    int? transcodingMaxAudioChannels,
    int? cpuCoreLimit,
    String? liveStreamId,
    bool? enableMpegtsM2TsMode,
    String? videoCodec,
    String? subtitleCodec,
    String? transcodeReasons,
    int? audioStreamIndex,
    int? videoStreamIndex,
    Context? context,
    int? maxRefFrames,
    bool? enableAdaptiveBitrateStreaming = false,
    bool? enableAudioVbrEncoding = true,
    RequestOptions? options,
  }) async* {
    final _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'mediaSourceId': mediaSourceId,
      r'maxAudioBitDepth': maxAudioBitDepth,
      r'tag': tag,
      r'deviceProfileId': deviceProfileId,
      r'playSessionId': playSessionId,
      r'segmentContainer': segmentContainer,
      r'segmentLength': segmentLength,
      r'minSegments': minSegments,
      r'static': staticValue,
      r'deviceId': deviceId,
      r'audioCodec': audioCodec,
      r'enableAutoStreamCopy': enableAutoStreamCopy,
      r'allowVideoStreamCopy': allowVideoStreamCopy,
      r'allowAudioStreamCopy': allowAudioStreamCopy,
      r'breakOnNonKeyFrames': breakOnNonKeyFrames,
      r'audioSampleRate': audioSampleRate,
      r'params': params,
      r'maxStreamingBitrate': maxStreamingBitrate,
      r'audioBitRate': audioBitRate,
      r'audioChannels': audioChannels,
      r'maxAudioChannels': maxAudioChannels,
      r'profile': profile,
      r'level': level,
      r'framerate': framerate,
      r'maxFramerate': maxFramerate,
      r'copyTimestamps': copyTimestamps,
      r'startTimeTicks': startTimeTicks,
      r'width': width,
      r'height': height,
      r'videoBitRate': videoBitRate,
      r'subtitleStreamIndex': subtitleStreamIndex,
      r'subtitleMethod': subtitleMethod?.toJson(),
      r'streamOptions': streamOptions,
      r'maxVideoBitDepth': maxVideoBitDepth,
      r'requireAvc': requireAvc,
      r'deInterlace': deInterlace,
      r'requireNonAnamorphic': requireNonAnamorphic,
      r'transcodingMaxAudioChannels': transcodingMaxAudioChannels,
      r'cpuCoreLimit': cpuCoreLimit,
      r'liveStreamId': liveStreamId,
      r'enableMpegtsM2TsMode': enableMpegtsM2TsMode,
      r'videoCodec': videoCodec,
      r'subtitleCodec': subtitleCodec,
      r'transcodeReasons': transcodeReasons,
      r'audioStreamIndex': audioStreamIndex,
      r'videoStreamIndex': videoStreamIndex,
      r'context': context?.toJson(),
      r'maxRefFrames': maxRefFrames,
      r'enableAdaptiveBitrateStreaming': enableAdaptiveBitrateStreaming,
      r'enableAudioVbrEncoding': enableAudioVbrEncoding,
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _headers = <String, dynamic>{};
    const Map<String, dynamic>? _data = null;
    final newOptions = newRequestOptions(options);
    newOptions.extra.addAll(_extra);
    newOptions.headers.addAll(_dio.options.headers);
    newOptions.headers.addAll(_headers);
    final _options = newOptions.copyWith(
      method: 'HEAD',
      baseUrl: _combineBaseUrls(_dio.options.baseUrl, baseUrl),
      responseType: ResponseType.stream,
      queryParameters: queryParameters,
      path: '/Audio/${itemId}/master.m3u8',
    )..data = _data;
    final _result = await _dio.fetch<ResponseBody>(_options);
    final _value = _result.data!.stream.map(utf8.decode);
    yield* _value;
  }

  @override
  Stream<String> getHlsVideoSegment({
    required String itemId,
    required String playlistId,
    required int segmentId,
    required String container,
    required int runtimeTicks,
    required int actualSegmentLengthTicks,
    bool? allowAudioStreamCopy,
    String? params,
    String? tag,
    String? deviceProfileId,
    String? playSessionId,
    String? segmentContainer,
    int? segmentLength,
    int? minSegments,
    String? mediaSourceId,
    String? deviceId,
    String? audioCodec,
    bool? enableAutoStreamCopy,
    bool? allowVideoStreamCopy,
    bool? staticValue,
    bool? breakOnNonKeyFrames,
    int? audioSampleRate,
    int? maxAudioBitDepth,
    int? audioBitRate,
    int? audioChannels,
    int? maxAudioChannels,
    String? profile,
    String? level,
    double? framerate,
    double? maxFramerate,
    bool? copyTimestamps,
    int? startTimeTicks,
    int? width,
    int? height,
    int? maxWidth,
    int? maxHeight,
    int? videoBitRate,
    Map<String, String?>? streamOptions,
    SubtitleMethod? subtitleMethod,
    int? maxRefFrames,
    int? maxVideoBitDepth,
    bool? requireAvc,
    bool? deInterlace,
    bool? requireNonAnamorphic,
    int? transcodingMaxAudioChannels,
    int? cpuCoreLimit,
    String? liveStreamId,
    bool? enableMpegtsM2TsMode,
    String? videoCodec,
    String? subtitleCodec,
    String? transcodeReasons,
    int? audioStreamIndex,
    int? videoStreamIndex,
    Context? context,
    int? subtitleStreamIndex,
    bool? enableAudioVbrEncoding = true,
    bool? alwaysBurnInSubtitleWhenTranscoding = false,
    RequestOptions? options,
  }) async* {
    final _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'runtimeTicks': runtimeTicks,
      r'actualSegmentLengthTicks': actualSegmentLengthTicks,
      r'allowAudioStreamCopy': allowAudioStreamCopy,
      r'params': params,
      r'tag': tag,
      r'deviceProfileId': deviceProfileId,
      r'playSessionId': playSessionId,
      r'segmentContainer': segmentContainer,
      r'segmentLength': segmentLength,
      r'minSegments': minSegments,
      r'mediaSourceId': mediaSourceId,
      r'deviceId': deviceId,
      r'audioCodec': audioCodec,
      r'enableAutoStreamCopy': enableAutoStreamCopy,
      r'allowVideoStreamCopy': allowVideoStreamCopy,
      r'static': staticValue,
      r'breakOnNonKeyFrames': breakOnNonKeyFrames,
      r'audioSampleRate': audioSampleRate,
      r'maxAudioBitDepth': maxAudioBitDepth,
      r'audioBitRate': audioBitRate,
      r'audioChannels': audioChannels,
      r'maxAudioChannels': maxAudioChannels,
      r'profile': profile,
      r'level': level,
      r'framerate': framerate,
      r'maxFramerate': maxFramerate,
      r'copyTimestamps': copyTimestamps,
      r'startTimeTicks': startTimeTicks,
      r'width': width,
      r'height': height,
      r'maxWidth': maxWidth,
      r'maxHeight': maxHeight,
      r'videoBitRate': videoBitRate,
      r'streamOptions': streamOptions,
      r'subtitleMethod': subtitleMethod?.toJson(),
      r'maxRefFrames': maxRefFrames,
      r'maxVideoBitDepth': maxVideoBitDepth,
      r'requireAvc': requireAvc,
      r'deInterlace': deInterlace,
      r'requireNonAnamorphic': requireNonAnamorphic,
      r'transcodingMaxAudioChannels': transcodingMaxAudioChannels,
      r'cpuCoreLimit': cpuCoreLimit,
      r'liveStreamId': liveStreamId,
      r'enableMpegtsM2TsMode': enableMpegtsM2TsMode,
      r'videoCodec': videoCodec,
      r'subtitleCodec': subtitleCodec,
      r'transcodeReasons': transcodeReasons,
      r'audioStreamIndex': audioStreamIndex,
      r'videoStreamIndex': videoStreamIndex,
      r'context': context?.toJson(),
      r'subtitleStreamIndex': subtitleStreamIndex,
      r'enableAudioVbrEncoding': enableAudioVbrEncoding,
      r'alwaysBurnInSubtitleWhenTranscoding':
          alwaysBurnInSubtitleWhenTranscoding,
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _headers = <String, dynamic>{};
    const Map<String, dynamic>? _data = null;
    final newOptions = newRequestOptions(options);
    newOptions.extra.addAll(_extra);
    newOptions.headers.addAll(_dio.options.headers);
    newOptions.headers.addAll(_headers);
    final _options = newOptions.copyWith(
      method: 'GET',
      baseUrl: _combineBaseUrls(_dio.options.baseUrl, baseUrl),
      responseType: ResponseType.stream,
      queryParameters: queryParameters,
      path: '/Videos/${itemId}/hls1/${playlistId}/${segmentId}.${container}',
    )..data = _data;
    final _result = await _dio.fetch<ResponseBody>(_options);
    final _value = _result.data!.stream.map(utf8.decode);
    yield* _value;
  }

  @override
  Stream<String> getLiveHlsStream({
    required String itemId,
    int? audioSampleRate,
    bool? staticValue,
    String? params,
    String? tag,
    String? deviceProfileId,
    String? playSessionId,
    String? segmentContainer,
    int? segmentLength,
    int? minSegments,
    String? mediaSourceId,
    String? deviceId,
    String? audioCodec,
    bool? enableAutoStreamCopy,
    bool? allowVideoStreamCopy,
    bool? allowAudioStreamCopy,
    bool? breakOnNonKeyFrames,
    String? container,
    int? maxAudioBitDepth,
    int? audioBitRate,
    int? audioChannels,
    int? maxAudioChannels,
    String? profile,
    String? level,
    double? framerate,
    double? maxFramerate,
    bool? copyTimestamps,
    int? startTimeTicks,
    int? width,
    int? height,
    int? videoBitRate,
    int? subtitleStreamIndex,
    SubtitleMethod? subtitleMethod,
    int? maxRefFrames,
    int? maxVideoBitDepth,
    bool? enableSubtitlesInManifest,
    bool? deInterlace,
    bool? requireNonAnamorphic,
    int? transcodingMaxAudioChannels,
    int? cpuCoreLimit,
    String? liveStreamId,
    bool? enableMpegtsM2TsMode,
    String? videoCodec,
    String? subtitleCodec,
    String? transcodeReasons,
    int? audioStreamIndex,
    int? videoStreamIndex,
    Context? context,
    Map<String, String?>? streamOptions,
    int? maxWidth,
    int? maxHeight,
    bool? requireAvc,
    bool? enableAudioVbrEncoding = true,
    bool? alwaysBurnInSubtitleWhenTranscoding = false,
    RequestOptions? options,
  }) async* {
    final _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'audioSampleRate': audioSampleRate,
      r'static': staticValue,
      r'params': params,
      r'tag': tag,
      r'deviceProfileId': deviceProfileId,
      r'playSessionId': playSessionId,
      r'segmentContainer': segmentContainer,
      r'segmentLength': segmentLength,
      r'minSegments': minSegments,
      r'mediaSourceId': mediaSourceId,
      r'deviceId': deviceId,
      r'audioCodec': audioCodec,
      r'enableAutoStreamCopy': enableAutoStreamCopy,
      r'allowVideoStreamCopy': allowVideoStreamCopy,
      r'allowAudioStreamCopy': allowAudioStreamCopy,
      r'breakOnNonKeyFrames': breakOnNonKeyFrames,
      r'container': container,
      r'maxAudioBitDepth': maxAudioBitDepth,
      r'audioBitRate': audioBitRate,
      r'audioChannels': audioChannels,
      r'maxAudioChannels': maxAudioChannels,
      r'profile': profile,
      r'level': level,
      r'framerate': framerate,
      r'maxFramerate': maxFramerate,
      r'copyTimestamps': copyTimestamps,
      r'startTimeTicks': startTimeTicks,
      r'width': width,
      r'height': height,
      r'videoBitRate': videoBitRate,
      r'subtitleStreamIndex': subtitleStreamIndex,
      r'subtitleMethod': subtitleMethod?.toJson(),
      r'maxRefFrames': maxRefFrames,
      r'maxVideoBitDepth': maxVideoBitDepth,
      r'enableSubtitlesInManifest': enableSubtitlesInManifest,
      r'deInterlace': deInterlace,
      r'requireNonAnamorphic': requireNonAnamorphic,
      r'transcodingMaxAudioChannels': transcodingMaxAudioChannels,
      r'cpuCoreLimit': cpuCoreLimit,
      r'liveStreamId': liveStreamId,
      r'enableMpegtsM2TsMode': enableMpegtsM2TsMode,
      r'videoCodec': videoCodec,
      r'subtitleCodec': subtitleCodec,
      r'transcodeReasons': transcodeReasons,
      r'audioStreamIndex': audioStreamIndex,
      r'videoStreamIndex': videoStreamIndex,
      r'context': context?.toJson(),
      r'streamOptions': streamOptions,
      r'maxWidth': maxWidth,
      r'maxHeight': maxHeight,
      r'requireAvc': requireAvc,
      r'enableAudioVbrEncoding': enableAudioVbrEncoding,
      r'alwaysBurnInSubtitleWhenTranscoding':
          alwaysBurnInSubtitleWhenTranscoding,
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _headers = <String, dynamic>{};
    const Map<String, dynamic>? _data = null;
    final newOptions = newRequestOptions(options);
    newOptions.extra.addAll(_extra);
    newOptions.headers.addAll(_dio.options.headers);
    newOptions.headers.addAll(_headers);
    final _options = newOptions.copyWith(
      method: 'GET',
      baseUrl: _combineBaseUrls(_dio.options.baseUrl, baseUrl),
      responseType: ResponseType.stream,
      queryParameters: queryParameters,
      path: '/Videos/${itemId}/live.m3u8',
    )..data = _data;
    final _result = await _dio.fetch<ResponseBody>(_options);
    final _value = _result.data!.stream.map(utf8.decode);
    yield* _value;
  }

  @override
  Stream<String> getVariantHlsVideoPlaylist({
    required String itemId,
    int? maxAudioBitDepth,
    String? params,
    String? tag,
    String? deviceProfileId,
    String? playSessionId,
    String? segmentContainer,
    int? segmentLength,
    int? minSegments,
    String? mediaSourceId,
    String? deviceId,
    String? audioCodec,
    bool? enableAutoStreamCopy,
    bool? allowVideoStreamCopy,
    bool? allowAudioStreamCopy,
    bool? breakOnNonKeyFrames,
    int? audioSampleRate,
    bool? staticValue,
    int? audioBitRate,
    int? audioChannels,
    int? maxAudioChannels,
    String? profile,
    String? level,
    double? framerate,
    double? maxFramerate,
    bool? copyTimestamps,
    int? startTimeTicks,
    int? width,
    int? height,
    int? maxWidth,
    int? maxHeight,
    int? videoBitRate,
    int? subtitleStreamIndex,
    Map<String, String?>? streamOptions,
    int? maxRefFrames,
    int? maxVideoBitDepth,
    bool? requireAvc,
    bool? deInterlace,
    bool? requireNonAnamorphic,
    int? transcodingMaxAudioChannels,
    int? cpuCoreLimit,
    String? liveStreamId,
    bool? enableMpegtsM2TsMode,
    String? videoCodec,
    String? subtitleCodec,
    String? transcodeReasons,
    int? audioStreamIndex,
    int? videoStreamIndex,
    Context? context,
    SubtitleMethod? subtitleMethod,
    bool? enableAudioVbrEncoding = true,
    bool? alwaysBurnInSubtitleWhenTranscoding = false,
    RequestOptions? options,
  }) async* {
    final _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'maxAudioBitDepth': maxAudioBitDepth,
      r'params': params,
      r'tag': tag,
      r'deviceProfileId': deviceProfileId,
      r'playSessionId': playSessionId,
      r'segmentContainer': segmentContainer,
      r'segmentLength': segmentLength,
      r'minSegments': minSegments,
      r'mediaSourceId': mediaSourceId,
      r'deviceId': deviceId,
      r'audioCodec': audioCodec,
      r'enableAutoStreamCopy': enableAutoStreamCopy,
      r'allowVideoStreamCopy': allowVideoStreamCopy,
      r'allowAudioStreamCopy': allowAudioStreamCopy,
      r'breakOnNonKeyFrames': breakOnNonKeyFrames,
      r'audioSampleRate': audioSampleRate,
      r'static': staticValue,
      r'audioBitRate': audioBitRate,
      r'audioChannels': audioChannels,
      r'maxAudioChannels': maxAudioChannels,
      r'profile': profile,
      r'level': level,
      r'framerate': framerate,
      r'maxFramerate': maxFramerate,
      r'copyTimestamps': copyTimestamps,
      r'startTimeTicks': startTimeTicks,
      r'width': width,
      r'height': height,
      r'maxWidth': maxWidth,
      r'maxHeight': maxHeight,
      r'videoBitRate': videoBitRate,
      r'subtitleStreamIndex': subtitleStreamIndex,
      r'streamOptions': streamOptions,
      r'maxRefFrames': maxRefFrames,
      r'maxVideoBitDepth': maxVideoBitDepth,
      r'requireAvc': requireAvc,
      r'deInterlace': deInterlace,
      r'requireNonAnamorphic': requireNonAnamorphic,
      r'transcodingMaxAudioChannels': transcodingMaxAudioChannels,
      r'cpuCoreLimit': cpuCoreLimit,
      r'liveStreamId': liveStreamId,
      r'enableMpegtsM2TsMode': enableMpegtsM2TsMode,
      r'videoCodec': videoCodec,
      r'subtitleCodec': subtitleCodec,
      r'transcodeReasons': transcodeReasons,
      r'audioStreamIndex': audioStreamIndex,
      r'videoStreamIndex': videoStreamIndex,
      r'context': context?.toJson(),
      r'subtitleMethod': subtitleMethod?.toJson(),
      r'enableAudioVbrEncoding': enableAudioVbrEncoding,
      r'alwaysBurnInSubtitleWhenTranscoding':
          alwaysBurnInSubtitleWhenTranscoding,
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _headers = <String, dynamic>{};
    const Map<String, dynamic>? _data = null;
    final newOptions = newRequestOptions(options);
    newOptions.extra.addAll(_extra);
    newOptions.headers.addAll(_dio.options.headers);
    newOptions.headers.addAll(_headers);
    final _options = newOptions.copyWith(
      method: 'GET',
      baseUrl: _combineBaseUrls(_dio.options.baseUrl, baseUrl),
      responseType: ResponseType.stream,
      queryParameters: queryParameters,
      path: '/Videos/${itemId}/main.m3u8',
    )..data = _data;
    final _result = await _dio.fetch<ResponseBody>(_options);
    final _value = _result.data!.stream.map(utf8.decode);
    yield* _value;
  }

  @override
  Stream<String> getMasterHlsVideoPlaylist({
    required String itemId,
    required String mediaSourceId,
    int? maxAudioBitDepth,
    String? tag,
    String? deviceProfileId,
    String? playSessionId,
    String? segmentContainer,
    int? segmentLength,
    int? minSegments,
    bool? staticValue,
    String? deviceId,
    String? audioCodec,
    bool? enableAutoStreamCopy,
    bool? allowVideoStreamCopy,
    bool? allowAudioStreamCopy,
    bool? breakOnNonKeyFrames,
    int? audioSampleRate,
    String? params,
    int? audioBitRate,
    int? audioChannels,
    int? maxAudioChannels,
    String? profile,
    String? level,
    double? framerate,
    double? maxFramerate,
    bool? copyTimestamps,
    int? startTimeTicks,
    int? width,
    int? height,
    int? maxWidth,
    int? maxHeight,
    int? videoBitRate,
    int? subtitleStreamIndex,
    SubtitleMethod? subtitleMethod,
    int? maxRefFrames,
    Map<String, String?>? streamOptions,
    bool? requireAvc,
    bool? deInterlace,
    bool? requireNonAnamorphic,
    int? transcodingMaxAudioChannels,
    int? cpuCoreLimit,
    String? liveStreamId,
    bool? enableMpegtsM2TsMode,
    String? videoCodec,
    String? subtitleCodec,
    String? transcodeReasons,
    int? audioStreamIndex,
    int? videoStreamIndex,
    Context? context,
    int? maxVideoBitDepth,
    bool? enableAdaptiveBitrateStreaming = false,
    bool? enableTrickplay = true,
    bool? enableAudioVbrEncoding = true,
    bool? alwaysBurnInSubtitleWhenTranscoding = false,
    RequestOptions? options,
  }) async* {
    final _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'mediaSourceId': mediaSourceId,
      r'maxAudioBitDepth': maxAudioBitDepth,
      r'tag': tag,
      r'deviceProfileId': deviceProfileId,
      r'playSessionId': playSessionId,
      r'segmentContainer': segmentContainer,
      r'segmentLength': segmentLength,
      r'minSegments': minSegments,
      r'static': staticValue,
      r'deviceId': deviceId,
      r'audioCodec': audioCodec,
      r'enableAutoStreamCopy': enableAutoStreamCopy,
      r'allowVideoStreamCopy': allowVideoStreamCopy,
      r'allowAudioStreamCopy': allowAudioStreamCopy,
      r'breakOnNonKeyFrames': breakOnNonKeyFrames,
      r'audioSampleRate': audioSampleRate,
      r'params': params,
      r'audioBitRate': audioBitRate,
      r'audioChannels': audioChannels,
      r'maxAudioChannels': maxAudioChannels,
      r'profile': profile,
      r'level': level,
      r'framerate': framerate,
      r'maxFramerate': maxFramerate,
      r'copyTimestamps': copyTimestamps,
      r'startTimeTicks': startTimeTicks,
      r'width': width,
      r'height': height,
      r'maxWidth': maxWidth,
      r'maxHeight': maxHeight,
      r'videoBitRate': videoBitRate,
      r'subtitleStreamIndex': subtitleStreamIndex,
      r'subtitleMethod': subtitleMethod?.toJson(),
      r'maxRefFrames': maxRefFrames,
      r'streamOptions': streamOptions,
      r'requireAvc': requireAvc,
      r'deInterlace': deInterlace,
      r'requireNonAnamorphic': requireNonAnamorphic,
      r'transcodingMaxAudioChannels': transcodingMaxAudioChannels,
      r'cpuCoreLimit': cpuCoreLimit,
      r'liveStreamId': liveStreamId,
      r'enableMpegtsM2TsMode': enableMpegtsM2TsMode,
      r'videoCodec': videoCodec,
      r'subtitleCodec': subtitleCodec,
      r'transcodeReasons': transcodeReasons,
      r'audioStreamIndex': audioStreamIndex,
      r'videoStreamIndex': videoStreamIndex,
      r'context': context?.toJson(),
      r'maxVideoBitDepth': maxVideoBitDepth,
      r'enableAdaptiveBitrateStreaming': enableAdaptiveBitrateStreaming,
      r'enableTrickplay': enableTrickplay,
      r'enableAudioVbrEncoding': enableAudioVbrEncoding,
      r'alwaysBurnInSubtitleWhenTranscoding':
          alwaysBurnInSubtitleWhenTranscoding,
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _headers = <String, dynamic>{};
    const Map<String, dynamic>? _data = null;
    final newOptions = newRequestOptions(options);
    newOptions.extra.addAll(_extra);
    newOptions.headers.addAll(_dio.options.headers);
    newOptions.headers.addAll(_headers);
    final _options = newOptions.copyWith(
      method: 'GET',
      baseUrl: _combineBaseUrls(_dio.options.baseUrl, baseUrl),
      responseType: ResponseType.stream,
      queryParameters: queryParameters,
      path: '/Videos/${itemId}/master.m3u8',
    )..data = _data;
    final _result = await _dio.fetch<ResponseBody>(_options);
    final _value = _result.data!.stream.map(utf8.decode);
    yield* _value;
  }

  @override
  Stream<String> headMasterHlsVideoPlaylist({
    required String itemId,
    required String mediaSourceId,
    int? maxAudioBitDepth,
    String? tag,
    String? deviceProfileId,
    String? playSessionId,
    String? segmentContainer,
    int? segmentLength,
    int? minSegments,
    bool? staticValue,
    String? deviceId,
    String? audioCodec,
    bool? enableAutoStreamCopy,
    bool? allowVideoStreamCopy,
    bool? allowAudioStreamCopy,
    bool? breakOnNonKeyFrames,
    int? audioSampleRate,
    String? params,
    int? audioBitRate,
    int? audioChannels,
    int? maxAudioChannels,
    String? profile,
    String? level,
    double? framerate,
    double? maxFramerate,
    bool? copyTimestamps,
    int? startTimeTicks,
    int? width,
    int? height,
    int? maxWidth,
    int? maxHeight,
    int? videoBitRate,
    int? subtitleStreamIndex,
    SubtitleMethod? subtitleMethod,
    int? maxRefFrames,
    Map<String, String?>? streamOptions,
    bool? requireAvc,
    bool? deInterlace,
    bool? requireNonAnamorphic,
    int? transcodingMaxAudioChannels,
    int? cpuCoreLimit,
    String? liveStreamId,
    bool? enableMpegtsM2TsMode,
    String? videoCodec,
    String? subtitleCodec,
    String? transcodeReasons,
    int? audioStreamIndex,
    int? videoStreamIndex,
    Context? context,
    int? maxVideoBitDepth,
    bool? enableAdaptiveBitrateStreaming = false,
    bool? enableTrickplay = true,
    bool? enableAudioVbrEncoding = true,
    bool? alwaysBurnInSubtitleWhenTranscoding = false,
    RequestOptions? options,
  }) async* {
    final _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'mediaSourceId': mediaSourceId,
      r'maxAudioBitDepth': maxAudioBitDepth,
      r'tag': tag,
      r'deviceProfileId': deviceProfileId,
      r'playSessionId': playSessionId,
      r'segmentContainer': segmentContainer,
      r'segmentLength': segmentLength,
      r'minSegments': minSegments,
      r'static': staticValue,
      r'deviceId': deviceId,
      r'audioCodec': audioCodec,
      r'enableAutoStreamCopy': enableAutoStreamCopy,
      r'allowVideoStreamCopy': allowVideoStreamCopy,
      r'allowAudioStreamCopy': allowAudioStreamCopy,
      r'breakOnNonKeyFrames': breakOnNonKeyFrames,
      r'audioSampleRate': audioSampleRate,
      r'params': params,
      r'audioBitRate': audioBitRate,
      r'audioChannels': audioChannels,
      r'maxAudioChannels': maxAudioChannels,
      r'profile': profile,
      r'level': level,
      r'framerate': framerate,
      r'maxFramerate': maxFramerate,
      r'copyTimestamps': copyTimestamps,
      r'startTimeTicks': startTimeTicks,
      r'width': width,
      r'height': height,
      r'maxWidth': maxWidth,
      r'maxHeight': maxHeight,
      r'videoBitRate': videoBitRate,
      r'subtitleStreamIndex': subtitleStreamIndex,
      r'subtitleMethod': subtitleMethod?.toJson(),
      r'maxRefFrames': maxRefFrames,
      r'streamOptions': streamOptions,
      r'requireAvc': requireAvc,
      r'deInterlace': deInterlace,
      r'requireNonAnamorphic': requireNonAnamorphic,
      r'transcodingMaxAudioChannels': transcodingMaxAudioChannels,
      r'cpuCoreLimit': cpuCoreLimit,
      r'liveStreamId': liveStreamId,
      r'enableMpegtsM2TsMode': enableMpegtsM2TsMode,
      r'videoCodec': videoCodec,
      r'subtitleCodec': subtitleCodec,
      r'transcodeReasons': transcodeReasons,
      r'audioStreamIndex': audioStreamIndex,
      r'videoStreamIndex': videoStreamIndex,
      r'context': context?.toJson(),
      r'maxVideoBitDepth': maxVideoBitDepth,
      r'enableAdaptiveBitrateStreaming': enableAdaptiveBitrateStreaming,
      r'enableTrickplay': enableTrickplay,
      r'enableAudioVbrEncoding': enableAudioVbrEncoding,
      r'alwaysBurnInSubtitleWhenTranscoding':
          alwaysBurnInSubtitleWhenTranscoding,
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _headers = <String, dynamic>{};
    const Map<String, dynamic>? _data = null;
    final newOptions = newRequestOptions(options);
    newOptions.extra.addAll(_extra);
    newOptions.headers.addAll(_dio.options.headers);
    newOptions.headers.addAll(_headers);
    final _options = newOptions.copyWith(
      method: 'HEAD',
      baseUrl: _combineBaseUrls(_dio.options.baseUrl, baseUrl),
      responseType: ResponseType.stream,
      queryParameters: queryParameters,
      path: '/Videos/${itemId}/master.m3u8',
    )..data = _data;
    final _result = await _dio.fetch<ResponseBody>(_options);
    final _value = _result.data!.stream.map(utf8.decode);
    yield* _value;
  }

  RequestOptions newRequestOptions(Object? options) {
    if (options is RequestOptions) {
      return options;
    }
    if (options is Options) {
      return RequestOptions(
        method: options.method,
        sendTimeout: options.sendTimeout,
        receiveTimeout: options.receiveTimeout,
        extra: options.extra,
        headers: options.headers,
        responseType: options.responseType,
        contentType: options.contentType.toString(),
        validateStatus: options.validateStatus,
        receiveDataWhenStatusError: options.receiveDataWhenStatusError,
        followRedirects: options.followRedirects,
        maxRedirects: options.maxRedirects,
        requestEncoder: options.requestEncoder,
        responseDecoder: options.responseDecoder,
        path: '',
      );
    }
    return RequestOptions(path: '');
  }

  RequestOptions _setStreamType<T>(RequestOptions requestOptions) {
    if (T != dynamic &&
        !(requestOptions.responseType == ResponseType.bytes ||
            requestOptions.responseType == ResponseType.stream)) {
      if (T == String) {
        requestOptions.responseType = ResponseType.plain;
      } else {
        requestOptions.responseType = ResponseType.json;
      }
    }
    return requestOptions;
  }

  String _combineBaseUrls(String dioBaseUrl, String? baseUrl) {
    if (baseUrl == null || baseUrl.trim().isEmpty) {
      return dioBaseUrl;
    }

    final url = Uri.parse(baseUrl);

    if (url.isAbsolute) {
      return url.toString();
    }

    return Uri.parse(dioBaseUrl).resolveUri(url).toString();
  }
}

// dart format on
